# Set penalty points
LATE_PENALTY = 1
VERY_LATE_LIMIT_HOURS = 1
VERY_LATE_PENALTY = 2
NO_SHOW_PENALTY = 2
JOKER_PROSECCO_PENALTY = 1

# GPIO
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
BLINK_DELAY = 0.3
ON_TIME_NUMBER_OF_BLINKS = 1
DEPARTING_NUMBER_OF_BLINKS = 2
LATE_NUMBER_OF_BLINKS = 1
VERY_LATE_NUMBER_OF_BLINKS = 2
SAFING_NUMBER_OF_BLINKS = 3
NUMBER_OF_LEDS = 8

# Set time limits
SAFING_LIMIT_MINUTES = 45
MEETING_TIME_SECONDS = "59"  # Set to 59 for allowing arrivals within the minute
