# Set penalty points
LATE_PENALTY = 1
VERY_LATE_LIMIT_HOURS = 1
VERY_LATE_PENALTY = 2
NO_SHOW_PENALTY = 2
JOKER_PROSECCO_PENALTY = 1

# GPIO
GREEN_LED_PIN = 17
BLUE_LED_PIN = 27
BLINK_DELAY = 0.3
ON_TIME_NUMBER_OF_BLINKS = 1
DEPARTING_NUMBER_OF_BLINKS = 2
LATE_NUMBER_OF_BLINKS = 1
VERY_LATE_NUMBER_OF_BLINKS = 2
SAFING_NUMBER_OF_BLINKS = 3

# Set time limits
SAFING_LIMIT_MINUTES = 30
MEETING_TIME_SECONDS = "59"  # Set to 59 for allowing arrivals within the minute
