# Set penalty points
LATE_PENALTY = 1
VERY_LATE_LIMIT_HOURS = 1
VERY_LATE_PENALTY = 2
NO_SHOW_PENALTY = 2
JOKER_PROSECCO_PENALTY = 1
GREEN_LED_PIN = 17
RED_LED_PIN = 27

# Set time limits
SAFING_LIMIT_MINUTES = 30
MEETING_TIME_SECONDS = "59"  # Set to 59 for allowing arrivals within the minute
